# Generated by Django 2.2.1 on 2019-06-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='cclick',
        ),
        migrations.AddField(
            model_name='shorturl',
            name='click',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
