# Generated by Django 2.2.1 on 2019-06-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20190606_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Short_urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField(unique=True, verbose_name='URL')),
                ('short_url', models.CharField(max_length=20)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('counter', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Url',
        ),
    ]
